### ISSUE TITLE
Error in stitch.hpp > Stitcher definition (missing 's')

### ISSUE THREAD

**Issue by cappelletto** [MecatronicaUSB/mosaic#4]
Missing 's' in variable definition prevents compilation of **stitch** module
This line
``
 int cell_div;                           //!< number (n) of cell divisions in grid detector (if used)
``
should be
``
 int cells_div;                           //!< number (n) of cell divisions in grid detector (if used)
``
Won't push the commit to **master** because it's a minor fix.

**Comment by vgarciac** [comment]
Already fixed, sorry about that!
