### ISSUE TITLE
Running **stitch** with no argument, fails

### ISSUE THREAD

**Issue by cappelletto** [MecatronicaUSB/mosaic#5]
When running **stitch** without any argument should prompt the usage or help information. Instead fails to load the image, which is expected to happen as no empty image validation is done. I think this can be also solved with a quickfix, yet i don't know yet how to handle empty cli calls with the new argument parsing library.

The error message:

> cappelletto@cueva:~/projects/mosaic/modules/stitch/build$
> 
>  ./stitch
> Built with OpenCV 3.2.0`
> 	Two images as imput	
> 	Feature extractor:	KAZE
> 	Feature Matcher:	FLANN
> 	Apply preprodessing:	false
> 	Use grid detection:	false
> OpenCV Error: Assertion failed (ssize.width > 0 && ssize.height > 0) in resize, file /media/documentos/install/OpenCV/opencv-3.2.0/modules/imgproc/src/imgwarp.cpp, line 3492
> terminate called after throwing an instance of 'cv::Exception'
>   what():  /media/documentos/install/OpenCV/opencv-3.2.0/modules/imgproc/src/imgwarp.cpp:3492: error: (-215) ssize.width > 0 && ssize.height > 0 in function resize
> 
> Aborted (core dumped)

**Comment by vgarciac** [comment]
Already fixed:
the library provide a build in solution for this cases, this is using the Grou::Validators option:
`args::Group op_data(parser, "Select imput data:", args::Group::Validators::AtLeastOne);`
another option is using the *argc* variable in main function, checking the numbers of input commands.
It is also posible set up this option for *detector* and *matcher* flags, but instead i decided to use a default selection for each one.
